"use client";

import { useState } from "react";

export default function Home() {
  const [balance, setBalance] = useState(4250);
    const [income, setIncome] = useState(2300);
      const [expenses, setExpenses] = useState(1200);

        return (
            <main
                  style={{
                          minHeight: "100vh",
                                  background:
                                            "radial-gradient(circle at top left, rgba(0,229,255,0.25), transparent 30%), radial-gradient(circle at bottom right, rgba(37,99,235,0.35), transparent 35%), linear-gradient(135deg, #020617, #081028, #0f172a)",
                                                    color: "white",
                                                            fontFamily: "Arial",
                                                                    padding: "40px 20px",
                                                                            textAlign: "center",
                                                                                  }}
                                                                                      >
                                                                                            <h1
                                                                                                    style={{
                                                                                                              fontSize: "56px",
                                                                                                                        color: "#67e8f9",
                                                                                                                                  textShadow: "0 0 25px rgba(103,232,249,0.8)",
                                                                                                                                            marginBottom: "10px",
                                                                                                                                                    }}
                                                                                                                                                          >
                                                                                                                                                                  F-IA
                                                                                                                                                                        </h1>

                                                                                                                                                                              <p style={{ opacity: 0.7 }}>Tu aplicación financiera inteligente</p>

                                                                                                                                                                                    <section
                                                                                                                                                                                            style={{
                                                                                                                                                                                                      margin: "30px auto",
                                                                                                                                                                                                                padding: "30px",
                                                                                                                                                                                                                          maxWidth: "360px",
                                                                                                                                                                                                                                    borderRadius: "24px",
                                                                                                                                                                                                                                              background: "rgba(17,28,68,0.72)",
                                                                                                                                                                                                                                                        border: "1px solid rgba(103,232,249,0.15)",
                                                                                                                                                                                                                                                                  boxShadow: "0 0 30px rgba(14,165,233,0.2)",
                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                        <h2>Balance Total</h2>
                                                                                                                                                                                                                                                                                                <h1>${balance.toLocaleString()}</h1>
                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                              display: "flex",
                                                                                                                                                                                                                                                                                                                                        gap: "20px",
                                                                                                                                                                                                                                                                                                                                                  justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                            flexWrap: "wrap",
                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                        padding: "24px",
                                                                                                                                                                                                                                                                                                                                                                                                                    width: "160px",
                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "22px",
                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "rgba(0,255,255,0.10)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>Ingresos</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1>${income.toLocaleString()}</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "24px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "160px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "22px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "rgba(140,82,255,0.14)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>Gastos</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1>${expenses.toLocaleString()}</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flexWrap: "wrap",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setExpenses(expenses + 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setBalance(balance - 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "14px 22px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "1px solid rgba(0,255,255,0.3)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "rgba(0,255,255,0.12)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                + Añadir gasto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setIncome(income + 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setBalance(balance + 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "14px 22px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid rgba(140,82,255,0.35)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "rgba(140,82,255,0.15)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          + Añadir ingreso
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }